name: Build Website (WASM)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-bindgen-cli
        run: cargo install -f wasm-bindgen-cli

      - name: Install wasm-opt
        run: cargo install wasm-opt --locked

      - name: Build for wasm32-unknown-unknown
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Generate JS bindings with wasm-bindgen
        run: |
          wasm-bindgen target/wasm32-unknown-unknown/release/svg-to-tvg.wasm \
            --target web \
            --no-typescript \
            --out-dir dist \
            --out-name svg-to-tvg

      - name: Copy index.html
        run: cp index.html dist/index.html

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: github-pages
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
